### ISSUE TITLE
Typing of internal arithmetics

### ISSUE THREAD

**Issue by m0ar** [m0ar/lollipop#41]
How can _add_, _mul_, _div_ etc be typed for both _int_ and _double_ without lollipop having type classes?

**Comment by JonasDuregard** [comment]
It can not. 

You have nothing in your current type data structure that would model this.

Of the top of my head I can think of a few ways to work around this that does not involve implementing type classes. 

One would be to have a special "TArithVar" type, that represents a special type variable that can only be unified with Int and Double (but they are otherwise treated as ordinary variables, so remember to include them when computing free variables, doing substitutions, declare them in type schemes etc). Or you could extend Scheme to have a separate list of which variables are arithmetic only, and then when instantiating this needs to be added to the environment somehow and considered when unifying. 

Or you could just skip doubles for now, or have separate operators for them. This is probably the way I would go if I where you.

**Comment by m0ar** [comment]
Aight, thanks for the input. We have decided to skip it for now and type them separately.
